name: auditfilesd9

# Run this workflow every time a new commit is pushed to the repo
on:
  push:
# The following will run on a schedule at 6am on Sundays
  schedule:
    - cron: '0 6 * * 0'

jobs:
  run-unit-tests:
    name: Run PHPUnit Tests
    runs-on:  ubuntu-latest
    env:
      MODULE: auditfiles
      COMPOSER_MEMORY_LIMIT: -1
      # Note, the username, password, port and db match mysql service setup.
      SIMPLETEST_DB: mysql://drupal:drupal@127.0.0.1:3306/auditfiles
      SIMPLETEST_BASE_URL: http://localhost:8888
    services:
      db:
        image: mysql:5.7
        ports:
        - 3306
        env:
          MYSQL_USER: drupal
          MYSQL_PASSWORD: drupal
          MYSQL_DATABASE: auditfiles
          MYSQL_ROOT_PASSWORD: user
        options: --health-cmd="mysqladmin ping" --health-interval=5s --health-timeout=2s --health-retries=3
    steps:
      - uses: actions/checkout@v2
      - name: Verify MySQL Connection
        env:
          PORT: ${{ job.services.db.ports[3306] }}
        run: |
          while ! mysqladmin ping -h"127.0.0.1" -P"$PORT" --silent; do
            sleep 1
          done
      - name: Set up php version (7.4)
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'
          extensions: date, dom, filter, gd, hash, json, mbstring, pcre, pdo, session, tokenizer, xml
          # Includes code coveage for phpunit, but disables xDebug
          coverage: pcov
      - name: Get Composer cache directory
        id: composercache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"
      - name: Cache composer dependencies
        uses: actions/cache@v2
        with:
          path: ${{ steps.composercache.outputs.dir }}
          # Use composer.json for key, if composer.lock is not committed
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.json') }}
          restore-keys: ${{ runner.os }}-composer-
      - name: Check php version (7.4)
        run: php --version
      - name: set up chromedriver for headless chrome
        uses: nanasess/setup-chromedriver@master
      - name: Install latest Google Chrome
        run: wget -q https://script.install.devinsideyou.com/google-chrome && chmod +x google-chrome
      # Comes from Bolt project, may not be necessary
      - name: Add chromedriver to PATH variable
        run: export PATH="$(pwd)/vendor/bin:${PATH}"
      - name: Echo out Path
        run: echo $PATH
      # Create new drupal project with Composer install
      - name: Install drupal
        run: composer update
      # Check for Drupal coding standards
      - name: Check for Drupal coding standards
        uses: guix77/phpcs-drupal-action@v1.0.0
      # Install Drupal for phpunit tests
      - name: Install Drupal for phpunit testing
        run: |
          $PROJECT_ROOT/vendor/bin/drush site-install standard --yes --account-pass=admin --db-url=$SIMPLETEST_DB
          $PROJECT_ROOT/vendor/bin/drush config-set system.performance css.preprocess 0 --yes
          $PROJECT_ROOT/vendor/bin/drush config-set system.performance js.preprocess 0 --yes
          $PROJECT_ROOT/vendor/bin/drush config-set system.logging error_level all --yes
      - name: Start HTTP server for testing
        run:  $PROJECT_ROOT/vendor/bin/drush runserver --default-server=builtin 8888 > /dev/null &       
      - name: Run PHPUnit Tests
        run: |
          $PROJECT_ROOT/vendor/bin/drush en simpletest
          $PROJECT_ROOT/vendor/bin/phpunit -c $DRUPAL_ROOT/core/phpunit.xml.dist --verbose --group=$MODULE $DRUPAL_ROOT/modules/contrib/$MODULE
          $PROJECT_ROOT/vendor/bin/drush pm:uninstall simpletest -y
